#!/bin/bash

# loan-calc: script to calculate monthly loan payments

PROGNAME=$(basename $0)

usage () {
	cat <<- EOF
	Usage: $PROGNAME PRINCIPAL INTEREST MONTHS

	Where:

	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% = 0.07)
	MONTHS is the lenght of the loan's term.

	EOF
}

if (($# != 3)); then
	usage
	exit 1
fi

# checking for valid input


if [[ $1 =~ ^[0-9]*\.?[0-9]*$ ]]; then
	principal=$1
else 
	echo "not a number"
	exit 1
fi

if [[ $2 =~ ^[0-9]*\.?[0-9]*$ ]]; then
	interest=$2
else
	echo "paramater 2 is not a number"
	exit 1
fi

if [[ $3 =~ ^[0-9]*$ ]]; then
	months=$3
else	
	echo "parameter 3 is not a number"
	exit 1
fi
	
bc <<- EOF
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((1 + i) ^ n)) / (((1 + i) ^ n) -1))
	print a, "\n"
EOF
