#!/bin/bash

# loan-calc: script to calculate monthly loan payments

PROGNAME=$(basename $0)

usage () {
	cat <<- EOF
	Usage: $PROGNAME PRINCIPAL INTEREST MONTHS

	Where:

	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% = 0.07)
	MONTHS is the lenght of the loan's term. MONTHS must me a whole number.

	EOF
}

if (($# != 3)); then
	usage
	exit 1
fi

# checking for valid input
reg="^[0-9]+(\.[0-9][0-9]?)?"  

if [[ $1 =~ $reg && $2 =~ $reg && $3 =~ ^[0-9]*$ ]]; then 
	principal=$1
	months=$3
	interest=$2
else 
	echo "One or more parameters are not valid"
	exit 1
fi
	
bc <<- EOF
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((1 + i) ^ n)) / (((1 + i) ^ n) -1))
	print a, "\n"
EOF
